" DO NOT EDIT: This file is automatically generated.

" Indents
set number
set shiftwidth=2
set tabstop=4
set autoindent
set smartindent
filetype plugin indent on

set clipboard+=unnamedplus

syntax enable

colorscheme dracula

" Mappings
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Buffers
noremap <C-S-h> bprev
noremap <C-S-l> bnext
" Term
tnoremap <Esc> <C-\><C-n>
