-- DO NOT EDIT: This file is automatically generated.

local wezterm = require 'wezterm'

local function font_with_fallback(name, params)
	local names = { name, "Noto Color Emoji", "FiraCode Nerd Font" }
	return wezterm.font_with_fallback(names, params)
end

return {
	audible_bell = "Disabled", 
	-- window
	window_decorations = "INTEGRATED_BUTTONS|RESIZE",
	window_background_opacity = .9,
	macos_window_background_blur = 30,

	native_macos_fullscreen_mode = true,

	hide_tab_bar_if_only_one_tab = true,
	tab_bar_at_bottom = true,
	use_fancy_tab_bar = false,
	enable_tab_bar = true,
	tab_max_width = 32,

	leader = { key="f", mods="CTRL", timeout_milliseconds=1000 },

	inactive_pane_hsb = {
		saturation = 0.5,
		brightness = 0.5,
	},

	color_scheme = "duskfox",
	colors = {
		tab_bar = {
			background = TAB_BAR_BG,
		},
	},

	-- default prog
	default_prog = {
		"/opt/homebrew/bin/tmux",
		"new",
	},

	keys = {
		{ key="-",  mods="SUPER", action=wezterm.action{ SplitVertical={ domain="CurrentPaneDomain" } } },
		{ key="|", mods="SUPER", action=wezterm.action{ SplitHorizontal={ domain="CurrentPaneDomain" } } },
		{ key="h",  mods="SUPER", action=wezterm.action{ ActivatePaneDirection="Left" } },
		{ key="l",  mods="SUPER", action=wezterm.action{ ActivatePaneDirection="Right" } },
		{ key="j",  mods="SUPER", action=wezterm.action{ ActivatePaneDirection="Down" } },
		{ key="k",  mods="SUPER", action=wezterm.action{ ActivatePaneDirection="Up" } },
		{ key="w",  mods="SUPER", action=wezterm.action{ CloseCurrentPane={confirm=true} } },
	},

	font = font_with_fallback("FiraCode Nerd Font"),
	font_size = 18.0
}

