[zsh.files]
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = "~/.zshrc"

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[wezterm.files]
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[vim.files]
"vimrc" = "~/.vimrc"

[neovim.files]
"vimrc" = { target = "~/.config/nvim/init.vim", type = "template", if = '(is_executable "nvim")'}

[hyper.files]
"hyper.js" = "~/.hyper.js"
